### ISSUE TITLE
Add new DEX [Tegro.Finance] on TON to Wallet

### ISSUE THREAD

**Issue by DeFiTON** [xtonwallet/web-extension-doc#1]
Good afternoon. Can add +1 more DEX on the TON blockchain to integration for your Wallet. Thanks!

Project site:
- https://tegro.finance/

Documentation and source code:
- https://github.com/orgs/TegroTON/repositories

- Roadmap and information:
https://tegro.gitbook.io/en/dex/

How to add a project? Integration Example, [DefiLllama](https://defillama.com/protocol/tegro-finance):
https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/tegro/index.js

**Comment by xtonwallet** [comment]
Your exchange already accepts our wallet (the user just needs to click on the TON wallet icon, some websites call it “web extension” for simplicity), we are modeling the API for the TON wallet and the extended API (https://github.com/ton-blockchain/TEPs/pull/105)

If you were referring to a hidden "swap" action for the next releases, then yes, we will add your DEX for instant exchange from the wallet in accordance with our roadmap.

**Comment by xtonwallet** [comment]
If this issue is not resolved, please contact us again.
